# Pip
# Github: https://github.com/geerlingguy/ansible-role-pip
- src: "geerlingguy.pip"
  version: "1.3.0"

# EPEL Repo configuration.
# Github repo: https://github.com/geerlingguy/ansible-role-repo-epel
- src: "geerlingguy.repo-epel"
  version: "1.2.3"

# Apache
# Github: https://github.com/geerlingguy/ansible-role-apache
- src: "geerlingguy.apache"
  version: "3.0.3"
