---
dependency:
  name: galaxy
  options:
    role-file: requirements.yaml
driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint
platforms:
  - name: instance
    box: ubuntu/bionic64
    memory: 1048
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: inspec
  lint:
    name: rubocop
    options:
      auto-correct: True
