---
# tasks file for tag1-letsencrypt

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Perform OS-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Initialize system paths and permissions
  become: true
  import_tasks: init.yaml
  tags:
    - letsencrypt

- name: Generate root key
  become: true
  openssl_privatekey:
    path: "{{ le_selfsign_base_dir }}/{{ le_selfsign_key_name }}"
  tags:
    - letsencrypt

- name: Create bogus chain.pem to appease apache
  become: true
  copy:
    content: "bogus"
    dest: "{{ le_selfsign_base_dir }}/{{ le_selfsign_chain_name }}"
  tags:
    - letsencrypt

- name: "Setup certs, chains, and private key paths"
  include_tasks: 
    file: generate.yml
    apply:
      tags:
        - letsencrypt
      become: true
  loop: '{{ apache_vhosts_ssl }}'
  loop_control:
    loop_var: vhost
  tags:
    - letsencrypt
  notify: restart apache

- name: Add cronjob for cert renewals
  become: true
  cron: 
    day: '*/7'
    job: certbot renew --post-hook "systemctl reload {{ le_webserver_unit_name }}"

- name: Disable default certbot timer
  become: true
  service:
    name: "{{ certbot_unit_name }}.timer"
    enabled: no
    state: stopped
  when: certbot_unit_name is defined

- name: Setup boulder server for testing
  import_tasks: acme-test.yaml
  become: true
  when: le_testing
  tags:
    - letsencrypt
